---
title: ""
output: html_document
---

<style>
body {
  margin: 0;
  font-family: "Helvetica", sans-serif;
  line-height: 1.1;
}
</style>

<div class="main-content">

<style>
.degree-entry {
  display: flex;
  justify-content: space-between;
  margin-bottom: 20px;
  width: 100%;
}

.degree-entry .left {
  flex: 1;                  /* take remaining space */
}

.degree-entry .right {
  text-align: right;
  min-width: 150px;         /* space for location/year */
}

.degree-entry .thesis {
  padding-left: 20px;       /* indent only thesis */
  display: block;           /* ensures it starts on new line */
}

.degree-entry .degree {
  font-style: italic;       /* italicize degree names */
}

.degree-entry .advisor {
  padding-left: 20px;       /* indent only advisor */
  display: block;
}
</style>


# Experience

--------

## Academic

::: {.degree-entry}
<div class="left">
**Columbia University Irving Medical Center**  
<span class="degree">PhD, Systems & Computational Biology (expected August 2026)</span> 
<span class="thesis">Thesis: *Machine learning methods to understand cancer-microbe interactions*</span>
<span class="advisor">Advisor: Prof. Tal Korem</span>
</div>
<div class="right">
**New York, NY**  
*2023 - present*
</div>
:::

::: {.degree-entry}
<div class="left">
**Columbia University, Fu Foundation School of Engineering and Applied Science**  
<span class="degree">Master of Science, Computer Science</span> (part-time) 
<span class="thesis">Thesis: *Contamination source modeling with SCRuB improves cancer phenotype prediction from microbiome data*</span>
<span class="advisor">Advisor: Prof. Tal Korem</span>
</div>
<div class="right">
**New York, NY**  
*2020 - 2022*
</div>
:::

::: {.degree-entry}
<div class="left">
**Columbia University, Fu Foundation School of Engineering and Applied Science**  
<span class="degree">Bachelor of Science, Applied Mathematics</span>
</div>
<div class="right">
**New York, NY**  
*2015 - 2019*
</div>
:::


--------

## Industry


::: {.degree-entry}
<div class="left">
**Optum Labs, UnitedHealth Group**  
<span class="degree">Principal Machine Learning Scientist</span>
<ul>
<li>Built predictive models for colorectal cancer screening</li>
<li>Novel transformer architectures to predict risk of multi-drug contraindications</li>
<li>Led research to develop and implement AI methods for automated prior authorization approvals</li>
</ul>
</div>
<div class="right">
**Minnetonka, MN**  
*2019 - 2023*
</div>
:::


::: {.degree-entry}
<div class="left">
**BNY Mellon**  
<span class="degree">Summer Analyst</span>
</div>
<div class="right">
**New York, NY**  
*2017*
</div>
:::



::: {.degree-entry}
<div class="left">
**Jazz House Kids**  
<span class="degree">Musician/Teaching Assistant</span>
</div>
<div class="right">
**Montclair, NJ**  
*2012 - 2019*
</div>
:::



---


## Awards & Honors

::: {.degree-entry}
<div class="left">
**Systems Biology T32 Award 1T32GM158494-01**  
<span class="subtext">Columbia University Irving Medical Center, Systems Biology</span>
</div>
<div class="right">
**New York, NY**  
2025
</div>
:::

::: {.degree-entry}
<div class="left">
**Institution Nominee, Regeneron Prize for Creative Innovation**  
<span class="subtext">Vagelos College of Physicians and Surgeons, Columbia University Irving Medical Center</span>
</div>
<div class="right">
**New York, NY**  
2025
</div>
:::

::: {.degree-entry}
<div class="left">
**Outstanding Poster Award**  
<span class="subtext">Columbia Systems Biology Department Retreat</span>
</div>
<div class="right">
**New York, NY**  
2023
</div>
:::









